import Head from "next/head";
import useSWRInfinite from 'swr/infinite'
import PokemonGrid from "@/components/PokemonGrid";
import { fetchPokemonList, getPokeapiKey } from "@/utils/pokemon";
import { getServerSavedPokemons } from "./api/saved";
import { getServerCatchedPokemons } from "./api/catched";

// export const getServerSideProps = (async () => {
//   // Fetch data from external API
//   const catchedPokemons = await getServerCatchedPokemons()
//   const savedPokemons = await getServerSavedPokemons()
//   // Pass data to the page via props
//   return { props: { savedPokemons, catchedPokemons } }
// })

export default function Home({ savedPokemons, catchedPokemons }) {
  const pokemonData = useSWRInfinite(getPokeapiKey, fetchPokemonList);
  return (
    <>
      <Head>
        <title>Pokemon Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonGrid {...pokemonData} savedPokemons={savedPokemons} catchedPokemons={catchedPokemons} />
    </>
  );
}
